### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by numToStr** [zhiburt/tabled#11]
I ran `cargo upgrade` and `papergrid` got updated to `0.1.11` and now I am unable to compile `tabled` because somehow `papergrid` contains a breaking change.

- Error
```bash
error[E0432]: unresolved import `papergrid::Alignment`
 --> /home/hello/.cargo/registry/src/github.com-1ecc6299db9ec823/tabled-0.1.3/src/alignment.rs:1:17
  |
1 | use papergrid::{Alignment, Entity, Grid, Settings};
  |                 ^^^^^^^^^ no `Alignment` in the root

error[E0432]: unresolved import `papergrid::Alignment`
   --> /home/hello/.cargo/registry/src/github.com-1ecc6299db9ec823/tabled-0.1.3/src/lib.rs:141:9
    |
141 | pub use papergrid::Alignment;
    |         ^^^^^^^^^^^^^^^^^^^^ no `Alignment` in the root

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0432`.
error: could not compile `tabled`

To learn more, run the command again with --verbose.
```

- Crates details
```yaml
tabled: "0.1.3"

# These are inside Cargo.lock
tabled_derive: "0.1.5"
papergrid: "0.1.11"
```

**Comment by zhiburt** [comment]
Hey @numToStr it's certainly strange.

Please check the latest version of `tabled` which has been just released.

**Comment by zhiburt** [comment]
Actually I can see why that happened.

While I was preparing a release I publish `papergrid` (internal dependency) first and only after a `tabled`. And you was building it just in this period of time where `papergrid` has a new code but `tabled` has not.

**Comment by zhiburt** [comment]
Anyway @numToStr thank you for reporting the issue.
