### ISSUE TITLE
Aesthetics versus Space Fog

### ISSUE THREAD

**Issue by omac777** [zhiburt/tabled#133]
I understand your emphasis on beautiful tables and layout.  It's appreciated for end user reports and views.

From a developer debugger perspective, there is room for improvement concerning what I'll call "Space Fog".
What is "Space Fog"?  It's the spaces presented before and after a displayed value that place cognitive load on the developer/debugger to determine where the actual value starts and ends.  This space fog is a burden.

Here's your table with space fog:
```
|         SomeValue         |
```

Here's a proposed table without space fog.  The delimiting "<<" and ">>" character groups sacrifice some aesthetics but aid in distinguishing where the actual value begins and ends:
```
|     <<SomeValue>>     |
```

Thank you for listening.

**Comment by zhiburt** [comment]
Hi @omac777 

I see what you mean.
Sometimes we'd love to distinguish between actual content and the spaces were added.

Do you see in what way it could be done?
Because clearly I don't see it as a default behaviour.

What could be done now is usage of `Format`.
See an example.

```rust
//! The example can be run by this command
//! `cargo run --example basic`

use tabled::{
    object::{Rows, Segment},
    Alignment, Format, Modify, Style, Table, Tabled,
};

#[derive(Tabled)]
struct Distribution {
    name: &'static str,
    #[tabled(display_with = "Self::display_based_on")]
    based_on: Option<&'static str>,
    is_active: bool,
    is_cool: bool,
}

impl Distribution {
    fn display_based_on(o: &Option<&'static str>) -> String {
        match o {
            &Some(s) => s.into(),
            None => "Independent".into(),
        }
    }
}

fn main() {
    let data = [
        Distribution {
            name: "Manjaro",
            based_on: Some("Arch"),
            is_cool: true,
            is_active: true,
        },
        Distribution {
            name: "Debian",
            based_on: None,
            is_cool: true,
            is_active: true,
        },
        Distribution {
            name: "Debian",
            based_on: None,
            is_cool: true,
            is_active: true,
        },
    ];

    let table = Table::new(&data)
        .with(Style::modern())
        .with(Modify::new(Rows::first()).with(Alignment::center()))
        .with(Modify::new(Rows::new(1..)).with(Alignment::left()))
        // resolving a 'space fog' issue
        .with(Modify::new(Segment::all()).with(Format::new(|s| format!("<<{}>>", s))));

    println!("{}", table);
}
```

![Screenshot_2022-05-16_22-00-31](https://user-images.githubusercontent.com/20165848/168663552-da69bac2-3074-4884-ad88-492b8319e2f5.png)

Please let me know what do you think.
And thank you for opening it.

**Comment by zhiburt** [comment]
By the way 1 idea came to me;

Maybe we could use your approach for a debug version of table?

Essentially when called like this.

```rust
println!("{:?}", table)
```

Currently table doesn't have a `Debug` implementation.

**Comment by omac777** [comment]
It's meticulous and beautiful!  I'm starring right now. i wish you a healthy and prosperous future.Cheers.

    On Wednesday, May 18, 2022, 07:31:57 a.m. EDT, Maxim Zhiburt ***@***.***> wrote:  
 
 


By the way 1 idea came to me;

Maybe we could use your approach for a debug version of table?

Essentially when called like this.
println!("{:?}", table)
Currently table doesn't have a Debug implementation.

**Comment by zhiburt** [comment]
@omac777 I wish you too all the best.

So can we close it?

Please let me know your thoughts on a `Debug` implementation if you have any.

**Comment by omac777** [comment]
Yes please close it.

    On Thursday, May 19, 2022, 04:36:07 p.m. EDT, Maxim Zhiburt ***@***.***> wrote:  
 
 


@omac777 I wish you too all the best.

So can we close it?

Please let me know your thoughts on a Debug implementation if you have any.
