### ISSUE TITLE
Readme spelling mistake

### ISSUE THREAD

**Issue by nskobelevs** [zhiburt/tabled#134]
Under Theme heading:

There are a list of ready to use styles. Each style can be **castomized**.

**Comment by zhiburt** [comment]
Hi @nskobelevs 

Back in the day, teachers always considered me bad at languages :disappointed_relieved: 

Thank you for pointing this out.

Maybe you want to make these fixes your self?

**Comment by zhiburt** [comment]
There's a few more from people on reddit.

> >There are a list of ready to use styles. Each style can be castomized.

> I suspect this is a typo.

ref: https://www.reddit.com/r/rust/comments/uqskpu/comment/i8tic40/?utm_source=share&utm_medium=web2x&context=3

> > For this porpouse you can use Border.
>
> Spotted this one too, not to pile on but to (hopefully) be helpful :)
> customized
> and
> purpose
> would be the fixes, respectively.

ref: https://www.reddit.com/r/rust/comments/uqskpu/comment/i8tx1lw/?utm_source=share&utm_medium=web2x&context=3

**Comment by nskobelevs** [comment]
>Maybe you want to make these fixes your self?

Sure, I'll make a PR.

**Comment by nskobelevs** [comment]
> MaxWidth sets a maximum width of an object. While tinkering content we don't forget about its color.

Can you clarify the second sentence please?

**Comment by zhiburt** [comment]
> > MaxWidth sets a maximum width of an object. While tinkering content we don't forget about its color.
> 
> Can you clarify the second sentence please?

Meaning:

When we cut or increase a width of a cell we keep correct colors.
*at least suppose to :)

**Comment by zhiburt** [comment]
closed by #138
