### ISSUE TITLE
Switch Symbol from String to Cow

### ISSUE THREAD

**Issue by zhiburt** [zhiburt/tabled#150]
The idea that someone could keep his styles statically so we could reduce allocations size.

**Comment by zhiburt** [comment]
Yes.... the descriptions is something which often lacking....

Hi @jk-gan sure

So the title is a bit outdated.
But the idea is just change these prefix and suffix to `Cow` if possible.

https://github.com/zhiburt/tabled/blob/308cdca66ad2dac07f83ab3eba9e289819d5782c/papergrid/src/color/ansi_color.rs#L6-L10

**Comment by fritzrehde** [comment]
I was looking through some old `good first issue` issues and found that this seems to have been solved, I think. At least the `AnsiColor` struct now uses `Cow` instead of `String`. Should this be closed now, or are there other places you would like to use `Cow` as well?

**Comment by zhiburt** [comment]
I think it's covered,
But funnily, after some thinking, I believe that we maybe need to revert this issue :)
At least to save a little memory.
Cause we have a `StaticColor` as a `&str` backed.

Sooooo
there's a bit of work with `color`s.

1. It'd be nice to copy the `const`s to the `StaticColor`.
2. Implement `CellOption` && `TableOption` for it.
3. Rephrase the comment  `/// Notice that the colors are constants so you can't combine them.` to `... at const time`.
4. Revert this (see above)
5. Maybe rename `StaticColor` to `Color` and `AnsiColor` to `ColorBuf`? (naming always hard, I like it but we have a `Color` trait already .... so need to think about it but the idea it be similar to `Path` and `PathBuf`)
6. After `4.` tabled::settings::Color shall be adjusted.

https://github.com/zhiburt/tabled/blob/74fcf7ade12d3ba5f461f67536f1a32245ef2192/tabled/src/settings/color/mod.rs#L46-L175

In case you'd like to tackle it, let me know, and probably it shall be moved to another issue.

Take care
