### ISSUE TITLE
Panic in Option::unwrap with empty BorderText

### ISSUE THREAD

**Issue by akanalytics** [zhiburt/tabled#164]
Great library. 

Get a panic sometimes. Seems to be related to a String::default() being passed to BorderText::first

.with(BorderText::first(&self.name))

Stack trace

thread 'search::engine::tests::example_search' panicked at 'called `Option::unwrap()` on a `None` value', /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/papergrid-0.4.0/src/lib.rs:2230:54
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::panicking::panic
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:48:5
   3: core::option::Option<T>::unwrap
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/option.rs:752:21
   4: papergrid::build_split_line_container
             at /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/papergrid-0.4.0/src/lib.rs:2230:20
   5: papergrid::build_grid
             at /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/papergrid-0.4.0/src/lib.rs:2106:30
   6: <papergrid::Grid as core::fmt::Display>::fmt
             at /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/papergrid-0.4.0/src/lib.rs:976:9
   7: core::fmt::write
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/fmt/mod.rs:1190:17
   8: core::fmt::Formatter::write_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/fmt/mod.rs:1644:9
   9: <tabled::table::Table as core::fmt::Display>::fmt
             at /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/tabled-0.7.0/src/table.rs:152:9

**Comment by zhiburt** [comment]
Hi @akanalytics 

It's a pitty that you've encountered a panic...
Panics are generally bad especially in a library layer.
*especially in `tabled` :)

>  String::default() being passed to BorderText::first

I think you're right....

This example causes panic.
Which to be honest I was not expect to.

```rust
String::default().lines().next().unwrap();
```

It must be fixed in `master` could you verify it?
Change your `Cargo.toml` section to.

```toml
tabled = { git = "https://github.com/zhiburt/tabled", branch = "master" }
```

Be aware that master branch has a few braking changes (as I remember the main one is a rename of `MaxWidth`, `MinWidth` to `Width`)

Thank you for opening the issue.

And take care.

**Comment by akanalytics** [comment]
Maxim

Yeah - works great.

Also seems to have fixed an issue I had with using BorderText::new with a
line number.

All good.

Andy

**Comment by zhiburt** [comment]
Good I'll close it then.

Take care.
