### ISSUE TITLE
How to conditionally format a field based on another field?

### ISSUE THREAD

**Issue by staticf0x** [zhiburt/tabled#168]
I have this struct:

```rust
#[derive(Debug, Tabled)]
struct Product {
    #[tabled(rename = "ID")]
    id: u32,
    #[tabled(rename = "Name")]
    name: String,
    price: Price,
    price_original: Price,
}
```

where `Price` is

```rust
#[derive(Debug, PartialEq)]
struct Price {
    price: Decimal,
    unit: Option<String>,
}
```

In order to display `Price` I implement `Display` for it:

```rust
impl Display for Price {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.price.to_string())
    }
}
```

And this works to just display the data. But now I want to have a condition: `if price < price_original` (discount), display that value with some color (only one cell). However, when implementing `Display` for `Price`, I can't reach other fields (self refers to `Price`, not `Product`).

Is this possible with tabled or do I have to kind of preprocess the structs into let's say `TableRow` that would contain already pre-colored strings?

**Comment by zhiburt** [comment]
Hi @staticf0x 

Thank you for opening this up.

Am I understand correctly that you want to show only 1 field instead of 2 based on same condition right?

Well then the better way is to combine the prices to a new struct and `impl std::fmt::Display` for it.

Back in the day I was pondering about something like your issue.
And came to this #13.
But I didn't came up with a good name of an attribute name :sweat_smile: 

So if #13 would be covered it would look like the following.

```rust
#[derive(Debug, Tabled)]
struct Product {
    #[tabled(rename = "ID")]
    id: u32,
    #[tabled(rename = "Name")]
    name: String,
    #[tabled(display_with("display_price", self)]
    price: Price,
    #[tabled(skip)]
    price_original: Price,
}

fn display_price(p: &Price, product: &Product) -> String { .. }
``` 

> Is this possible with tabled or do I have to kind of preprocess the structs into let's say TableRow that would contain already pre-colored strings?

One of possibilities.

You could do the following today too.
But it's still not what you were looking for I bet.

```rust
#[derive(Debug, Tabled)]
struct Product {
    #[tabled(rename = "ID")]
    id: u32,
    #[tabled(rename = "Name")]
    name: String,
    #[tabled(display_with("display_prices")]
    prices: Prices,
}

struct Prices(Price, Price);

fn display_prices(p: &Prices) -> String { .. }
``` 

Maybe you have some ideas here?

**Comment by staticf0x** [comment]
Hi, yes #13 would solve this very nicely :)

I'm at this point:

```rust
#[derive(Tabled)]
struct TableRow {
    #[tabled(rename = "ID")]
    id: u32,
    #[tabled(rename = "Name")]
    name: String,
    #[tabled(rename = "Price")]
    price: String,
    #[tabled(rename = "Original Price")]
    price_original: String,
}

impl TableRow {
    fn from_product(product: &Product) -> Self {
        let price_str: String;

        if product.price < product.price_original {
            price_str = product.price.to_string().color("green").to_string();
        } else {
            price_str = product.price.to_string();
        }

        return Self {
            id: product.id,
            name: product.name.clone(),
            price: price_str,
            price_original: product.price_original.to_string(),
        };
    }
}
```

So now instead of feeding `Product` structs into tabled, I convert them to `TableRow` and do the conditional formatting there. It kinda works, I have the numbers in green (using `colored` crate), but the output is messed up:

![image](https://user-images.githubusercontent.com/44530786/173088802-810d9ec9-acc6-498d-ac02-06fcca59b825.png)


The content of `price_str` is `[src/main.rs:52] price_str.clone() = "\u{1b}[32m52.90\u{1b}[0m"`.

Is this expected?

**Comment by zhiburt** [comment]
Could you check your `Cargo.toml` and turn `color` feature on for `tabled`.

```toml
tabled = { version = "*", features = ["color"] }
```

**Comment by zhiburt** [comment]
OK you made me to do that.....

The name is not perfect `args` but this is what I decided ....

You can switch to this branch

```toml
tabled = { git = "https://github.com/zhiburt/tabled", branch = "tabled-with-display-self" features = ["color"] }
```

And then you can do the following.

```rust
#[derive(Debug, Tabled)]
struct Product {
    #[tabled(rename = "ID")]
    id: u32,
    #[tabled(rename = "Name")]
    name: String,
    #[tabled(rename = "Price", display_with("display_price", args))]
    price: String,
    #[tabled(rename = "Original Price")]
    price_original: String,
}

fn display_price(product: &Product) -> String {
        if product.price < product.price_original {
            product.price.to_string().color("green").to_string()
        } else {
            product.price.to_string()
        }
}
```

**Comment by staticf0x** [comment]
Awesome! That works very well and the resulting code is now very clean in my opinion.

**Comment by zhiburt** [comment]
I've merged it to master so you can use it from there but better use `rev` pointing to a specific commit as master branch may have some breaking changes.

If you feel it's closed.
Please close this issue or let me know.

And take care.

**Comment by staticf0x** [comment]
Yes thank you very much!
