### ISSUE TITLE
Why not insert a method to change the headers ?

### ISSUE THREAD

**Issue by mzanrosso** [zhiburt/tabled#17]
Hello everyone, my use-case is to map a lot of different struct in one struct that implement the tabled trait; my problem is that I cannot easily change the headers since every struct need different header names.

Now I have this structure:
`println!("{}", Table::new(testtable).to_string());`

but I need something similar to this (the headers object could be a Vec of String):
`println!("{}", Table::new(testtable).with_headers(headers).to_string());`

is anyone interested in implement this ?

**Comment by zhiburt** [comment]
Hey @mzanrosso,

Thank you for opening the issue.

As I understand you basically have a structure with a huge list of fields and you need to rename them correct?

You could use a `Format` modifier to achieve this. though it would be as convenient.
I could create an util function for this I ?hope?.

Didn't test it but it got to work I guess.

```rust
fn change_header(table: &mut Table, mut data: Vec<String>) -> &mut Table {
   table.with(Modify::new(Row(..1)).with(|s: &str| {
      match data.pop() {
          Some(new_s) => s,
          None => s.to_string(),
      }
   }))
}

Table::new(testtable).with(
```

**Comment by zhiburt** [comment]
The following example works.

```
fn main() {
    let data = [
        ["Hello World", "123123123231"],
        ["Hello World", "zxczczxcxczxczxc"],
        ["Hello World", "[[[[[[[[[[[[[[[[["],
    ];

    let mut table = Table::new(&data).with(Style::github_markdown());

    let headers = vec!["HEADER_1".to_string(), "HEADER_2".to_string()];

    let count_columns = <[&str; 2] as Tabled>::headers().len();
    for i in 0..count_columns {
        let header = headers[i].clone();
        table = table.with(Modify::new(tabled::Cell(0, i)).with(move |_: &str| header.clone()));
    }

    println!("{}", table);
}
```

Overall I agree we need better way.
I'll tackle it tommorow.

Good night! :)

**Comment by mzanrosso** [comment]
@zhiburt - Thanks for the answer. Yeah I saw that with some trick you can achieve this result but it's not the simplest and the smartest way to do it, since I need to replicate this code a lot of times, this header change has to be one line maximum.

**Comment by zhiburt** [comment]
I've added a `FormatFrom` which you can use.

https://github.com/zhiburt/tabled/blob/b10b0d3c8939c7d85cbee5c52bb2069f87e0f027/examples/format.rs#L36-L40

But after a sleep I kind of started to think you may better follow another approach.
Could you show actually how you compose your structure?

**Comment by zhiburt** [comment]
I was just wondering if a `#[header(inline)]` help you?

**Comment by mzanrosso** [comment]
Hey @zhiburt  thanks for the examples; even if I think it can be more clean and simple, this is fair enough for my use-case:
```
println!(
        "{}",
        Table::new(testtable)
            .with(Modify::new(Row(0..1)).with(FormatFrom(vec![
                "test1", "test2", "test3", "test4", "test5", "test6"
            ])))
            .to_string()
    );
```

**Comment by zhiburt** [comment]
Great.

>even if I think it can be more clean and simple,

I've done that in such way because it can be used in a more broad list of cases.

Could you show your vision on how it would be more simple and clean?
As you showed here?

```
println!("{}", Table::new(testtable).with_headers(headers).to_string());
```

And ones again could you show your data structure? :smile: 
I just tend to think that `#[header(inline)]` is a good fit in your case.
