### ISSUE TITLE
Custom hyperlinks cause wrong column borders

### ISSUE THREAD

**Issue by avsaase** [zhiburt/tabled#176]
Hi,

Thanks for making this awesome crate. 

I'm making a command line tool that prints a table with some URLs. The URLs are too long to display in full so instead I want to show a custom text (see [here](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda) for more info on this). 

Here's a MWE using `tabled`:

```
use tabled::{object::Segment, Alignment, Modify, Table, Tabled};

#[derive(Debug, Tabled)]
struct MyStruct {
    name: String,
    #[tabled(display_with = "display_option_link")]
    link: Option<Link>,
    #[tabled(display_with = "display_option_link")]
    link2: Option<Link>,
}

#[derive(Debug, Tabled)]
struct Link {
    pub text: String,
    pub url: String,
}

impl Link {
    pub fn new(text: String, url: String) -> Self {
        Self { text, url }
    }
}

fn display_option_link(o: &Option<Link>) -> String {
    match o {
        Some(s) => format!("\u{1b}]8;;{}\u{1b}\\{}\u{1b}]8;;\u{1b}\\", s.url, s.text),
        None => format!(""),
    }
}

fn main() {
    let items = vec![
        MyStruct {
            name: "Google".to_string(),
            link: Some(Link::new(
                "click".to_string(),
                "https://www.google.com".to_string(),
            )),
            link2: Some(Link::new(
                "click".to_string(),
                "https://www.google.com".to_string(),
            )),
        },
        MyStruct {
            name: "Bing".to_string(),
            link: Some(Link::new(
                "click".to_string(),
                "http://www.bing.com".to_string(),
            )),
            link2: Some(Link::new(
                "click".to_string(),
                "http://www.bing.com".to_string(),
            )),
        },
    ];

    let table = Table::new(items)
        .with(Modify::new(Segment::all()).with(Alignment::left()))
        .to_string();
    println!("{}", table)
}
```

This prints
```
+--------+---------------------------------------+---------------------------------------+
| name   | link                                  | link2                                 |
+--------+---------------------------------------+---------------------------------------+
| Google | click | click |
+--------+---------------------------------------+---------------------------------------+
| Bing   | click    | click    |
+--------+---------------------------------------+---------------------------------------+
```

with the links clickable in a supported terminal emulator.

As you can see the column borders are not placed correctly. Interestingly, when I try to do this with the `cli-table` crate the result is the same. But when I directly print `items` using this code the spacing is correct.
```
for i in items {
    println!("{} | {} | {}", i.name, display_option_link(&i.link), display_option_link(&i.link2))
}
```

I'm very new to rust and I don't fully understand the string formatting system so I'm not sure if this is a bug or that I'm doing something wrong.

**Comment by zhiburt** [comment]
Hi @avsaase 

Thank you open opening the 

So essentially hyperlinks are a list of ansi characters.
`tabled` doesn't handle it by default. (mainly because of the idea that some people don't use them and it a bit `slower` then not to use them).

What you need to do is;
Go to your `Cargo.toml`.
And change the `tabled` import to require `color` feature.

```toml
tabled = { version = "0.7.0", features = ["color"] }
```

PS: It's showed in a `README.md` already, but maybe you have an idea where we could update the documentation in order to make it more clear?

**Comment by avsaase** [comment]
Thanks so much. That indeed solved the problem. Maybe you can add a note that the color feature handles ansi characters and this allows making custom hyperlinks, with a link to that gist? Basically what you just told me :).

**Comment by avsaase** [comment]
I see this is already clearly noted in the README and I just completely missed it.
