### ISSUE TITLE
examples panic

### ISSUE THREAD

**Issue by fdncred** [zhiburt/tabled#179]
i made [this ](https://gist.github.com/fdncred/2fca37ce4a71c2e8b9551a50abc30741/) for the core-team to see some of the functionality of tabled, and discovered that the `margin` and `highlight` examples panic. feel free to use that md file in your examples folder if you want to. it would make it easier to see what the examples look like. :)

**Comment by zhiburt** [comment]
Hi @fdncred 

Good catch; (as always).

I've forgot to update the examples.

> feel free to use that md file in your examples folder if you want to. it would make it easier to see what the examples look like. :)

it maybe a good idea.

**Comment by zhiburt** [comment]
Must be fixed in 0968bffe3d3a1428a9de775038021f72631ae2da
