### ISSUE TITLE
Make derive an optional feature

### ISSUE THREAD

**Issue by oberblastmeister** [zhiburt/tabled#190]
Derive is useful but not always needed, and can cause longer compile times. It is pretty standard to have an optional feature to enable derive. This is done in `serde`, `clap`, and more. I am interested to implement this if it is okay.

**Comment by oberblastmeister** [comment]
Wow I can't believe I didn't see that there is already the derive feature

**Comment by zhiburt** [comment]
Hi @oberblastmeister

That's a great observation.
I also came to it probably a week a ago.

It's already in `master` but not yet released.
I'll plan to do it this week hopefully.

Thanks for the care.
Have a great time.
