### ISSUE TITLE
How to remove column header

### ISSUE THREAD

**Issue by oberblastmeister** [zhiburt/tabled#193]
`set_columns([])` in the builder seems like the closest thing, but outputs an extra newline. Is there a way to remove the column header?

**Comment by zhiburt** [comment]
Hi @oberblastmeister 

You can use `builder.remove_columns();`

```rust
fn main() {
    let oceans = [("oberblastmeister", "4 hours ago"), ("zhiburt", "now")];

    let mut builder = Table::builder(&oceans);
    builder.remove_columns();

    let table = builder.build();

    println!("{}", table);
}

```

Though now I question my self maybe it's too verbose.
I remember I was thinking about it but chosen a new method as you see.
Maybe if `set_columns([])` called we could consider it a remove.
What do you think?

**Comment by oberblastmeister** [comment]
Is this function not released yet? I couldn't find it in the docs.

**Comment by zhiburt** [comment]
Unfortunately not yet.
But I am planning to release it in a few days.

**Comment by zhiburt** [comment]
You could you `Disable::Row(..1)` instead.

**Comment by oberblastmeister** [comment]
Closing as there is a new release. Thanks!

**Comment by matteosantama** [comment]
> Meanwhile you can use `Disable::Row(..1)` instead.

This works to hide the column names, but it doesn't preserve the width of the columns. Is there a way to both hide the column names and preserve the width of the columns?

My application is reading live data, and printing one row at a time to console. Perhaps there is a better way to achieve this "live feed" behavior?

**Comment by zhiburt** [comment]
Hi @matteosantama 

There's many ways to do that I tend to believe;
I got this

Funnily I haven't figured out a short one :smile: :disappointed: :disappointed_relieved: 

If you need further help; please file a new issue, as it's a bit unrelated to original one.

Take care.

### Example

`RemoveHeaderTransparentlyForWidth` is the key here

```rust
use tabled::{
    grid::{
        config::ColoredConfig,
        dimension::{CompleteDimensionVecRecords, Estimate, PeekableDimension},
        records::{
            vec_records::{CellInfo, VecRecords},
            Resizable,
        },
    },
    settings::{object::Columns, Alignment, Style, TableOption},
    Table, Tabled,
};

#[derive(Debug, Tabled)]
struct Weather {
    temperature_c: f64,
    wind_ms: f64,
}

impl Weather {
    fn new(temperature_c: f64, wind_ms: f64) -> Self {
        Self {
            temperature_c,
            wind_ms,
        }
    }
}

#[derive(Debug, Tabled)]
struct Location(
    #[tabled(rename = "latitude")] f64,
    #[tabled(rename = "longitude")] f64,
);

fn main() {
    let weather_data = [
        Weather::new(1.0, 3.0),
        Weather::new(-20.0, 30.0),
        Weather::new(40.0, 100.0),
    ];

    let mut weather_table = Table::new(weather_data);
    weather_table
        .with(Style::empty())
        .modify(Columns::single(1), Alignment::right())
        .modify(Columns::first(), Alignment::center())
        .with(RemoveHeaderTransparentlyForWidth);

    println!("{weather_table}");
}

struct RemoveHeaderTransparentlyForWidth;

impl<'a> TableOption<VecRecords<CellInfo<String>>, ColoredConfig, CompleteDimensionVecRecords<'a>>
    for RemoveHeaderTransparentlyForWidth
{
    fn change(
        self,
        recs: &mut VecRecords<CellInfo<String>>,
        cfg: &mut ColoredConfig,
        dims: &mut CompleteDimensionVecRecords<'a>,
    ) {
        let widths = PeekableDimension::width(&*recs, cfg);
        dims.set_widths(widths);
        dims.estimate(&*recs, cfg);
        recs.remove_row(0);
    }
}
```

```text
      1           3 
     -20         30 
     40         100 
```

### No alloc

```rust
use tabled::{
    grid::{
        dimension::{CompactGridDimension, Dimension},
        records::IterRecords,
    },
    settings::{Alignment, Style},
    tables::CompactTable,
};

fn main() {
    let data = [
        ["temperature", "wind m/s", "note"],
        ["+10", "3", ""],
        ["+40", "10", "......."],
        ["-20", "1.1", ""],
    ];

    let widths =
        CompactGridDimension::width(IterRecords::new(&data, 3, Some(5)), &Default::default());
    let dims = WidthDimension(widths);

    // skip the header
    let data = &data[1..];

    let weather_table = CompactTable::with_dimension(data, dims)
        .columns(3)
        .with(Style::modern())
        .with(Alignment::right())
        .to_string();

    println!("{weather_table}");
}

/// A dimension value.
#[derive(Debug, Clone)]
struct WidthDimension(Vec<usize>);

impl Dimension for WidthDimension {
    fn get_width(&self, column: usize) -> usize {
        self.0[column]
    }

    fn get_height(&self, _row: usize) -> usize {
        unreachable!("")
    }
}
```

```text
┌─────────────┬──────────┬─────────┐
│         +10 │        3 │         │
│─────────────┼──────────┼─────────│
│         +40 │       10 │ ....... │
│─────────────┼──────────┼─────────│
│         -20 │      1.1 │         │
└─────────────┴──────────┴─────────┘
```

> This works to hide the column names, but it doesn't preserve the width of the columns. Is there a way to both hide the column names and preserve the width of the columns?

You mean that in cases that the data in the columns is smaller than a name of columns.
Right?

> My application is reading live data, and printing one row at a time to console. Perhaps there is a better way to achieve this "live feed" behavior?

likely;

if you expect to have exact column sizes (based on the column names) no super fancy style and single line content,
I'd do `CompactTable`, this way no allocations will be made, and it'll generally faster because of this.

**Comment by matteosantama** [comment]
Wow, thank you for such a thoughtful response! I will give that a try, and follow up in a new issue if I encounter problems.
