### ISSUE TITLE
Support psql-like 'expanded display'

### ISSUE THREAD

**Issue by sd2k** [zhiburt/tabled#20]
psql has an 'expanded display' mode, which converts the format to two columns, with the header in the first column and value in the second, and one row printed at a time:

```
peter@localhost testdb=> \a \t \x
Output format is aligned.
Tuples only is off.
Expanded display is on.
peter@localhost testdb=> SELECT * FROM my_table;
-[ RECORD 1 ]-
first  | 1
second | one
-[ RECORD 2 ]-
first  | 2
second | two
-[ RECORD 3 ]-
first  | 3
second | three
-[ RECORD 4 ]-
first  | 4
second | four
```

(example taken from the bottom of https://www.postgresql.org/docs/current/app-psql.html).

It would be great if something similar could be supported by this crate, as it helps a lot when rows have so many columns that they span multiple lines.

Thanks for the crate by the way, it's working wonderfully!

**Comment by zhiburt** [comment]
Hi @sd2k,
thank you for making up this proposal.

I think it might be useful.
I'll try to work on this.

One question got to my mind though:
what happens if a value is multiline string?

There could be used `{:?}` to have a one line with escaped symbols.
Or we could expand `|` rows like this.

```
-[ RECORD 1 ]-
first  | Hello
       | World
```

**Comment by zhiburt** [comment]
Please take a look at [example](https://github.com/zhiburt/tabled/pull/21/commits/a8a8a57c0fe3975265f0efd57f128a6b4758b69e)

And is there any modificators I should add for such a type? Like custom width, custom space, a way to put a custom RECORD name or something.

**Comment by sd2k** [comment]
Thanks @zhiburt!

I did a little investigation into psql's formatting:

```
postgres=# insert into test values (0, 'this is a short string
postgres'# with a newline', 'a really really really really really really really really really really really really really really really really really really really really really really really really really long string');
INSERT 0 1
postgres=# select * from test;
-[ RECORD 1 ]-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
a | 0
b | this is a short string                                                                                                                                                                      +
  | with a newline
c | a really really really really really really really really really really really really really really really really really really really really really really really really really long string

```

So it looks like psql follows your second example 🙂 

---

Edit: just saw your new comment, that looks ace! I can think of a couple of potentially useful customizations:

1. removing the quotes around each field (perhaps that should just be the default behaviour, to match psql?)
2. setting the max width for the second column
3. configuring whether the second column should wrap if it exceeds the max width, rather than truncating

Actually for 3. I was about to create a separate issue to enable wrapping in the default `Table` layout - I'll do that separately.

So cool that you got this done so quickly!

**Comment by zhiburt** [comment]
I've updated #21 so it now has a methods for max width.

But I started to feel that maybe its too much of customization :( as we do a couple of allocation because of this.

Are you satisfied with how it looks?

*The names of methods a bit worry me :disappointed:*

**Comment by zhiburt** [comment]
It turns out that the format isn't as plain.

There's a `+` sign and the length of `------` in header pattern must be the same for all records.
All of this requires allocations which makes me sad :disappointed:
