### ISSUE TITLE
Recognize terminal links when doing wrap/truncate

### ISSUE THREAD

**Issue by zhiburt** [zhiburt/tabled#203]
As was pointed out in #201 currently when we do width manipulations we break links.
The idea to fix it to preserve links content.

If the logic will be quite complex it's better to be hidden by some feature flag.

**Comment by dandavison** [comment]
Hi @zhiburt, I might have a go at this.

**Comment by zhiburt** [comment]
Hey @dandavison sorry for the delay,

Thanks for the proposition.

I've implemented 1 wrap version already (there 2 version 1 which tries to keep words and another which doesn't).
So I don't know, maybe I'll continue? (It takes me a while.....)

I've seen your message about implementation proposal.
I stuck with regex. Maybe `vte` would be more efficient, but ... I don't know.

PS: `wrap.rs` is **quite** a messy place (duplication here and there etc.) I think you would not like the experience :) (joking)
