### ISSUE TITLE
How to limit the number of decimal places for f64 cells?

### ISSUE THREAD

**Issue by ethercrow** [zhiburt/tabled#204]
I'm trying to print a bunch of floating point data in a table:

```
    #[derive(Tabled)]
    struct Row {
        thing: String,
        value1: f64,
        value2: f64,
        ...
    }
```

The numbers come out with the default huge number of decimal places, like `13.922228060881016`. I'd like to see them as `13.92`.

Is there an easier way to limit those other than doing the pre-formatting myself so that the Row fields are already strings instead of floats? I looked at the readme and the `format*.rs` examples but didn't notice anything obviously applicable.

**Comment by zhiburt** [comment]
Hi @ethercrow,
It could be done using `Format` but I'd do it differently.

Here's an example.

```rust
#[derive(Tabled)]
struct Row {
    thing: String,
    #[tabled(display_with = "float2")]
    value1: f64,
    #[tabled(display_with = "float2")]
    value2: f64,
}

fn float2(n: &f64) -> String {
    format!("{:.2?}", n)
}
```

**Comment by ethercrow** [comment]
Thank you @zhiburt, that seems straightforward enough!
