### ISSUE TITLE
An easy way to remove columns by name?

### ISSUE THREAD

**Issue by aldanor** [zhiburt/tabled#216]
Say, you have

```rust
#[derive(Tabled)]
struct Entry { a: ..., b: ..., c: ...}
let entries: Vec<Entry> = ...;
let table = entries.table();
```

If you wanted to remove columns 'a' and 'c' (depending on some runtime condition), you currently have to do something like

```rust
// definitely not the most obvious way...
use tabled::Tabled;
let i = Entry::headers().iter().position(|h| h == "c").unwrap();
let table = table.with(Disable::Column(i..=i));
let i = Entry::headers().iter().position(|h| h == "a").unwrap();
let table = table.with(Disable::Column(i..=i));
```

Also note that if you remove 'a' first, removing 'c' will not work, because now the indices would have shifted...

Would it be nice if you could just do something like this instead?

```rust
let table = table.with(RemoveColumn::new("a")).with(RemoveColumn::new("c"));
```

(or something along those lines)

**Comment by zhiburt** [comment]
A think it makes sense.
I'll work on it.

**Comment by aldanor** [comment]
Another use case (just to add) - is modifying columns by name. E.g., you have an entry with 20 fields and you want to align the "Foo" column. Doing it by a hard-coded index would be extremely fragile as opposed to being able to refer to columns by string name.

**Comment by zhiburt** [comment]
Hi @aldanor I think it must be closed.
I also addressed your proposal with targeting columns by name.

See

https://github.com/zhiburt/tabled/blob/9b26d481b8e18ac3ef5e1d69c7fdf6a5f4e58319/examples/disable.rs#L25-L38
