### ISSUE TITLE
Add option to wrap when `MaxWidth` is configured

### ISSUE THREAD

**Issue by sd2k** [zhiburt/tabled#22]
It would be really nice to be able to wrap wide columns onto newlines, rather than truncating them. Something like:

```
    let expected = concat!(
        "| id | destribution |    link    |\n",
        "|----+--------------+------------|\n",
        "| 0  |    Fedora    | https://ge |\n",
        "|    |              | tfedora.or |\n",
        "|    |              |     g/     |\n",
        "| 2  |   OpenSUSE   | https://ww |\n",
        "|    |              | w.opensuse |\n",
        "|    |              |   .org/    |\n",
        "| 3  |  Endeavouro  | https://en |\n",
        "|    |      s       | deavouros. |\n",
        "|    |              |    com/    |\n",
    );
```

when the max width is set to 10.

---

I had a go at this, and have the above test passing, but it required changing the public API of `MaxWidth` and didn't work great with type inference. Happy to push it up so you can take a look though.

**Comment by zhiburt** [comment]
I think it may make sense to have.
But I am not sure in which way.

You proposed the same feature for #20.
And I initially did implemented that.
But then I started to think that if someone what to do this he can just use a formatting function.

```rust
    let table = Table::new(&data)
        .with(Modify::new(Column(2)).with(|s: &str| {
            s.lines()
                .map(|l| l.chars().take(MAX_CHARS).collect::<String>())
                .collect::<Vec<String>>()
                .join("\n")
        }))
```

**Comment by zhiburt** [comment]
But yes it seems too complex too put this on user (+ it doesn't deal with colors).
I mean yes probably we could have this

**Comment by sd2k** [comment]
Huh, I didn't actually realise it was possible to do with a formatting function. Good to know! I can see there's a separate PR in progress for the MaxWidth wrapping though, which is amazing - thanks again 👍

**Comment by zhiburt** [comment]
@sd2k it actually suppose to be finished.
I'll merge it right when you say that its OK :)

*I didn't figure out how to commit to your branch which is unfortunate, but as you may have seen your commit is preserved correctly there.

**Comment by sd2k** [comment]
Just tested this out too, it looks great, thanks a lot for adding the functionality :)
