### ISSUE TITLE
Documentation seems to have a build problem on docs.rs

### ISSUE THREAD

**Issue by larswirzenius** [zhiburt/tabled#230]
When I look at https://docs.rs/crate/tabled/latest I see:

>  docs.rs failed to build tabled-0.8.0 

The build log includes this:

~~~
[INFO] [stderr] error: Package `tabled v0.8.0 (/opt/rustwide/workdir)` does not have the feature `unstable-doc`
~~~

I'm afraid I didn't investigate further.

**Comment by zhiburt** [comment]
Hi @larswirzenius you're 100% right,

Unfortunately it's more than a month it stays broken......
I just noticed it not soon enough............................... (my mistake....)

I'm hoping to publish a new version of `tabled` soon so it will be fixed.
(I hope this week).

Thanks you for reporting.

There was quite a few changes so the README in master is not relevant in some parts.
Till than you can use https://github.com/zhiburt/tabled/blob/d055382d4865622d94800cfd5fd1ef2784e1b14b/README.md for `0.8` version.

Sorry once again....... It's 100% on me :disappointed: 

Take care.

**Comment by larswirzenius** [comment]
Hey, there's no need to be sorry. Especially not if you only do this in your free time. Anything you do is a gift to the world.

Thank you for the crate. I've written code for table generation before, although never as ambitious as your crate, and I really appreciate not having to write that once again.

**Comment by zhiburt** [comment]
Eventually...
Must be fixed https://docs.rs/tabled/0.9.0-fix.docs.rs.4/tabled/
