### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by songlinshu** [zhiburt/tabled#245]
Hi,How does this work?
![image](https://user-images.githubusercontent.com/45619496/197333540-b355ccfb-4b7e-4218-b8df-97e99f5e6b5d.png)

**Comment by zhiburt** [comment]
Hi @songlinshu 

> Hi,How does this work?

Let me guess you ask "Is it possible to do the following using `tabled`'?

**Comment by songlinshu** [comment]
Yes

**Comment by zhiburt** [comment]
Beside this part, it's possible.

<img width="62" alt="image" src="https://user-images.githubusercontent.com/20165848/197417146-ef7e909a-564d-465e-bc1a-ffbdd5f4cec3.png">

See the example.

https://github.com/zhiburt/tabled/tree/master/examples#span
https://github.com/zhiburt/tabled/blob/master/examples/span.rs

**Comment by songlinshu** [comment]
Thank !

**Comment by CGMossa** [comment]
Close this issue please.
