### ISSUE TITLE
Rows deleted during rotation when number of fields is greater than number of records

### ISSUE THREAD

**Issue by Gryphon-** [zhiburt/tabled#246]
I am attempting to use tabled to display data that can have the number of fields exceeding the number of elements. Under this scenario, the data in the fields after the (number of elements + 1) are blank and printed as empty boxes as shown below. I can mitigate this by adding sufficient dummy records, then rotating, and then deleting the columns, but I don't think this is desired behavior.

```
#[derive(Tabled)]
struct Info {
    checksum: u64,
    version: u32,
    file_size: u32,
    offset: u32,
}

let info1 = Info::Default();
let info2 = Info::Default();

let mut table = [&info1, &info2].table();
table.with(Rotate::Left);
println("{}", table);


+-----------+----+----+
|           |    |    |
+-----------+----+----+
| file_size | 16 | 16 |
+-----------+----+----+
| version   | 1  | 1  |
+-----------+----+----+
| checksum  | 0  | 0  |
+-----------+----+----+
```

**Comment by zhiburt** [comment]
> ```
> +-----------+----+----+
> |           |    |    |
> +-----------+----+----+
> | file_size | 16 | 16 |
> +-----------+----+----+
> | version   | 1  | 1  |
> +-----------+----+----+
> | checksum  | 0  | 0  |
> +-----------+----+----+
> ```

You mean that after `Rotate::Left` we are losing here `offset` field, right?

**Comment by zhiburt** [comment]
I believe must be fixed

Could you patch your `Cargo.toml` to use `master` branch and verify it?

```rust
use tabled::{Rotate, TableIteratorExt, Tabled};

#[derive(Tabled, Default)]
struct Info {
    checksum: u64,
    version: u32,
    file_size: u32,
    offset: u32,
}

fn main() {
    let info1 = Info::default();
    let info2 = Info::default();

    let mut table = [&info1, &info2].table();
    println!("{}", table);

    table.with(Rotate::Left);

    println!("{}", table);
}
```

**Comment by Gryphon-** [comment]
Thanks for the quick update! Yeah that seems to resolve the issue.
