### ISSUE TITLE
Lingering `println!()` in `json_to_table`

### ISSUE THREAD

**Issue by Veetaha** [zhiburt/tabled#253]
https://github.com/zhiburt/tabled/blob/aad12c9636bb8cf3517db093888501c1c0e04124/json_to_table/src/table.rs#L450

The latest version of `json_to_table` outputs some debug stuff directly to `stdout`. I assume this was an oversight leftover from debugging

**Comment by zhiburt** [comment]
here we go.......................................

**Comment by zhiburt** [comment]
Sorry.......................

Thanks for opening an issue.

**Comment by zhiburt** [comment]
must be fixed with `0.3.1`.

Thanks, and sorry once again.

**Comment by Veetaha** [comment]
Np, by coincidence I was just trying out tabled ✔️
