### ISSUE TITLE
'Tabled' derive macro with optional fields

### ISSUE THREAD

**Issue by danieleades** [zhiburt/tabled#265]
For my use-case it is common for fields in a table row to be empty, indicated by an `Optional::None` value. This doesn't seem to be supported, since `Option` doesn't implement `std::fmt::Display`.

Is there anyway around this, or do i need to construct the table manually?

**Comment by zhiburt** [comment]
Hi @danieleades 

If I understood you correctly,
You can use `display_with`.

```rust
use tabled::Tabled;

#[derive(Tabled)]
pub struct MyRecord {
    pub id: i64,
    #[tabled(display_with = "display_option")]
    pub valid: Option<bool>
}

fn display_option(o: &Option<bool>) -> String {
    match o {
        Some(s) => format!("is valid thing = {}", s),
        None => format!("is not valid"),
    }
}
```

There was a though to provide these functions like `display_option`, `display_result` or even consider it a default.
But it was (and still) not clear whereas it's worth it.
