### ISSUE TITLE
Add a table consistency property based test

### ISSUE THREAD

**Issue by zhiburt** [zhiburt/tabled#269]
It's need to

1. Add a test (better a few tests) which takes some data, and some settings (padding, row spans, columns spans, etc.).
2. Build a table with the settings and the data given.
3. And then check whether the table string contains artifacts (meaning broken).

    It can be done by chaning a style's left/right corner to some character (for example `%`),
    and checking if the character always stays right/left most.

_________________

We already have 1 similar test

https://github.com/zhiburt/tabled/blob/294118fa5a81f14c981856d560256c74f8011716/tests/builder_test.rs#L741-L758

__________________

To give you an idea this is how a broken table may look like

![image](https://user-images.githubusercontent.com/20165848/214837946-f43e406b-52af-41e5-b9f6-a9e86c002619.png)

**Comment by arunma** [comment]
@zhiburt - Relatively new to Rust.  Made an attempt. Greatly appreciate it if you could review and see if this aligns with the expectation.
