### ISSUE TITLE
Color rendering error

### ISSUE THREAD

**Issue by quuc** [zhiburt/tabled#27]
Cargo.toml:
```toml
[dependencies]
colored = "2.0.0"
[dependencies.tabled]
version = "0.3.0"
default-features = false
features = ["color"]
```
main.rs
```rust
use colored::Colorize;
use tabled::{Column, Format, Full, MaxWidth, Modify, Style, Table, Tabled};

#[derive(Tabled)]
struct Language {
    name: &'static str,
    designed_by: &'static str,
    invented_year: usize,
}

impl Language {
    fn new(name: &'static str, designed_by: &'static str, invented_year: usize) -> Self {
        Self {
            name,
            designed_by,
            invented_year,
        }
    }
}

fn main() {
    let languages = vec![
        Language::new("C 💕", "Dennis  Ritchie", 1972),
        Language::new("Rust 👍", "Graydon Hoare", 2010),
        Language::new("Go", "Pob Pike", 2009),
    ];

    let table = Table::new(languages)
        .with(Modify::new(Full).with(MaxWidth::wrapping(8)))
        .with(Modify::new(Column(..1)).with(Format(|s| s.red().to_string())))
        .with(Modify::new(Column(1..2)).with(Format(|s| s.green().to_string())))
        .with(Modify::new(Column(2..)).with(Format(|s| s.blue().to_string())))
        .with(Style::pseudo());
    println!("{}", table);
}
```
<img width="509" alt="2021-10-18 11 28 37" src="https://user-images.githubusercontent.com/54758066/137666372-866b15a4-8cb2-4227-922f-7e8a9633fb42.png">
Why is "_by" blue and not green?

Also, why is "Ritchie" white and not green?

<img width="1867" alt="2021-10-18 11 29 35" src="https://user-images.githubusercontent.com/54758066/137666386-0b989358-df8c-43cb-a301-76dd3edfad33.png">
I used a small terminal, so I limited the width of the table.

**Comment by zhiburt** [comment]
Hi @cu233,
thank you for opening the issue.

At first I was thinking it is an inner error.
But it turns out not :relieved: 

The thing is that all modifications to table applied one after another.
So in your example we at fist split the content `MaxWidth` and then do a colorization.

> ```rust
>    let table = Table::new(languages)
>        .with(Modify::new(Full).with(MaxWidth::wrapping(8)))
>        .with(Modify::new(Column(..1)).with(Format(|s| s.red().to_string())))
>        .with(Modify::new(Column(1..2)).with(Format(|s| s.green().to_string())))
>        .with(Modify::new(Column(2..)).with(Format(|s| s.blue().to_string())))
>        .with(Style::pseudo());
> ```

Try to reverse this order.

```rust
    let table = Table::new(languages)
        .with(Modify::new(Column(..1)).with(Format(|s| s.red().to_string())))
        .with(Modify::new(Column(1..2)).with(Format(|s| s.green().to_string())))
        .with(Modify::new(Column(2..)).with(Format(|s| s.blue().to_string())))
        .with(Modify::new(Full).with(MaxWidth::wrapping(8)))
        .with(Style::pseudo());
 ```

Such behavior may seem a bit undocumented,
let me know if you feel it is.
