### ISSUE TITLE
Add `has_left`, `has_right`, methods to `RawStyle`

### ISSUE THREAD

**Issue by zhiburt** [zhiburt/tabled#270]
It was apparently missed previously.

Additionally I think it's useful to
+ Add `get_borders()` method
+ rename `set_left_intersection` to `set_intersection_left` to match other functions as they end with `left/right` suffix.

**Comment by scirin** [comment]
@zhiburt , Hey - perhaps you meant **get**_left/right/top/bottom_intersection should be changed to end with suffix

**Comment by zhiburt** [comment]
It was addressed at the time of `0.12.0`
