### ISSUE TITLE
Example output migration

### ISSUE THREAD

**Issue by IsaacCloos** [zhiburt/tabled#296]
>I wonder what do you think about putting the results of examples right to the head comment of the example?
We have  the results in examples/README.md but I wonder if it would be any useful to have it right there.

_Originally posted by @zhiburt in https://github.com/zhiburt/tabled/issues/294#issuecomment-1450169714_

**Comment by zhiburt** [comment]
I am actually thinking maybe adding a description to the example would be more valuable e.g.

> This example demonstrates padding changes of a particular cell.
> `Padding` is stand for left/right/top/bottom inner indent of a cell.

**Comment by IsaacCloos** [comment]
I'd be happy to make these changes 😄  

Do you approve of these new goals for this issue:
- [ ] remove [/tabled/examples/readme](https://github.com/zhiburt/tabled/blob/master/tabled/examples/README.md)
- [ ] update all examples with brief descriptions (like you demonstrated in this [comment](https://github.com/zhiburt/tabled/issues/296#issuecomment-1458189149))

**Comment by zhiburt** [comment]
> remove [/tabled/examples/readme](https://github.com/zhiburt/tabled/blob/master/tabled/examples/README.md)

Welllllll I guess we better do not delete it:)
I believe it's quite informative; to see what kind of tables we may build.

I guess my original comment was **misleading**;
I guess the example files better be short (some of them are quite big which might be hard to get already).
And why having output in comment if we could do an assert in the code so it could be used as test as well?

__________________________

1. the idea to have a descriptions of; "What the example does and what it tries to accomplish" is good.
2. the output example in a top comment might be unnecessary? @IsaacCloos 
3. do not delete the readme :)

**Comment by IsaacCloos** [comment]
I will write up a short form explanation of every example in the project ✏️ 

Thanks for clarifying 😄
