### ISSUE TITLE
Overlapping Panels throw uncaught errors

### ISSUE THREAD

**Issue by IsaacCloos** [zhiburt/tabled#319]
### Issue and Steps to Reproduce

When using the [Panel](https://github.com/zhiburt/tabled/blob/master/tabled/src/settings/panel/mod.rs) setting, if you insert horizontal and vertical panels that overlap each other it causes the application to crash.

You can easily test this scenario by visiting the Panel example, and changing either of the vertically injected panels to 1-4; conflicting with the previously applied table-length horizontal panels. 
https://github.com/zhiburt/tabled/blob/837bed213e824ced96cd7e9dc18a0c8c439fc314/tabled/examples/panel.rs#L43-L57

### Expected Behavior

It would be in keeping with other fault-tolerant table settings that if these functions cannot resolve, they simply return without making any modifications. Although perhaps, for Panel, it could be an option to have the most recently applied panel nest within those before it? Maybe look something like this (rather than crash):

<img width="549" alt="Screenshot 2023-03-31 at 12 42 04 PM" src="https://user-images.githubusercontent.com/46393653/229180332-38a943ac-fa83-426d-928d-76fb52b45262.png">

```rust
table
    .with(Panel::header("Tabled Releases"))
    .with(Panel::footer(format!("N - {}", DATA.len())))
    .with(Panel::vertical(0, "Some text goes here"))
    .with(Panel::vertical(4, "Some text goes here")) // <-- changed
```

### Additional Details
* I also tested this scenario with [Span](https://github.com/zhiburt/tabled/blob/master/tabled/src/settings/span/mod.rs) and it crashes as well. It would seem that conflicting spans are the real issue I'm documenting here 😆

**Comment by zhiburt** [comment]
Thanks for report.

> Although perhaps, for Panel, it could be an option to have the most recently applied panel nest within those before it? Maybe look something like this (rather than crash):

Well I am not sure.
Basically you're saying to put put a new column bellow 1st horizontal row/ and above 2nd horizontal row.
But I kind of find it not intuitive enough?

It actually was working something like this previously (`0.10` works this way).
But I was thinking that it was hard to use.
Specifically we were able to set a specific position `(row, column)` from which we insert horizontal/vertical line.

There's one argument here that is there any way to insert a new line column in specific position? (on `0.10` we had as I've described).
Now we seems don't?

Maybe I shall restore back that I am not sure....
Or maybe add some other way to do so.

**Comment by zhiburt** [comment]
Like this

```rust
test_table!(
    panel_horizontal_set_2,
    create_table::<3, 3>()
        .with(Style::psql())
        .with(Panel::horizontal(0).text("Linux Distributions"))
        .with(Panel::vertical(0).text("asd"))
        .with(Panel::vertical(5).text("asd"))
        .with(Panel::vertical(3).row(1).text("asd")),
    " asd |      Linux Distributions      |          | asd "
    "     +---+----------+-----+----------+----------+     "
    "     | N | column 0 | asd | column 1 | column 2 |     "
    "     | 0 |   0-0    |     |   0-1    |   0-2    |     "
    "     | 1 |   1-0    |     |   1-1    |   1-2    |     "
    "     | 2 |   2-0    |     |   2-1    |   2-2    |     "
);
```
