### ISSUE TITLE
Hidden fields shouldn't need to implement Display

### ISSUE THREAD

**Issue by nrdxp** [zhiburt/tabled#32]
I have a field of a struct which I do not plan to show in the table output. However, despite adding:
```rust
    #[header(hidden = true)]
    foo: SomeType
```
I still have an error compiling the struct, saying `SomeType` doesn't implement display. Obviously, I don't want to go through the trouble of implementing `Display` for a type I don't plan to list in the table. If possible, there should be a way to completely disable parsing for this field so that not having `Display` implemented for a field which is hidden doesn't error out.

**Comment by zhiburt** [comment]
Hi @nrdxp 

Great observation,
I never thought about it :)

Thank you for bringing  this up.

I'll try to work on this tomorrow.

**Comment by zhiburt** [comment]
Hey @nrdxp 

Could you show the exact `struct` you're using?

Because I as see hiding fields in `struct`s and `tuple`s works well in master branch already.

The only issue I've spotted is when it's used in enum with `#[field(inline)]` is this your case?

Here's tests

https://github.com/zhiburt/tabled/blob/061ccd7c4e9c0aecc8420df803026c063b64ff09/tests/derive_test.rs#L593-L715

**Comment by zhiburt** [comment]
By they how do you think maybe its worth to rename `hidden` to `ignore`?

**Comment by zhiburt** [comment]
*Coincidentally was closed after #34 merge :disappointed_relieved:

**Comment by zhiburt** [comment]
ping

**Comment by nrdxp** [comment]
Hey sorry, my notifications got flooded with other things and I haven't seen any of this til now. Unfortunately I don't have any of the code I was using at the time left over, I switched to using [prettytable-rs](https://github.com/phsym/prettytable-rs) for the time being, although I would much prefer printing the tables directly from structs as this crate provides, rather than manually building the tables as I'm doing with prettytable, so I'd eventually like to give this another shot.

**Comment by zhiburt** [comment]
Understood.

Let me know if you'll encounter any difficulties on the second shot :)

If you don't mind I'll close the issue then.

And Yes.
Happy New Year.
