### ISSUE TITLE
error[E0433]: failed to resolve: could not find `tabled` in the list of imported crates

### ISSUE THREAD

**Issue by zjp-CN** [zhiburt/tabled#332]
In case people comes here for finding the reason and solution about the error.

```rust
error[E0433]: failed to resolve: could not find `tabled` in the list of imported crates
  --> tests/xxx.rs:33:17
   |
33 | #[derive(Debug, tabled::Tabled, Serialize)]
   |                 ^^^^^^^^^^^^^^ could not find `tabled` in the list of imported crates
```

### Reproduce:

* crate `a` uses crate `testing` as a direct dependency, and doesn't (want to) use `tabled` as a direct dependency
* crate `testing` uses `tabled` as a direct dependency, and reexports `Tabled`, like `pub use tabled::{self, Table, Tabled};`
* when crate `a` uses the `use testing::tabled; #[derive(tabled::Tabled)] ...`, it fails as shown above[^reexport]

[^reexport]: or `pub use tabled::{Table, Tabled};` in `testing`, and `use testing::Tabled; #[derive(Tabled)]` in `a`

### Reason

Due to #315 ,`#[derive(tabled::Tabled)]` will expand to `impl ::tabled::Tabled for ...`. But crate `a` doesn't have `::tabled` since `tabled` isn't a direct dependency in Cargo.toml.

### Solution

The obvious solution is to import `tabled` in crate `a` as  a direct dependency. But it makes the crate `testing` useless because we actually don't want to import `tabled` in two places.

So, to pretend we have a direct `tabled` dependency, [`extern crate ... as ...`](https://doc.rust-lang.org/reference/items/extern-crates.html) can help. This works:

```rust
// in crate `testing`
pub use tabled::{Table, Tabled};

// in crate `a`
extern crate testing as tabled; // solution

#[derive(tabled::Tabled)]
...
```

**Comment by zhiburt** [comment]
Hi @zjp-CN 

I guess you're correct?
So I wonder why you've closed it?
