### ISSUE TITLE
Option to color whole cell contents including justification space 

### ISSUE THREAD

**Issue by tyilo** [zhiburt/tabled#337]
The following code:

```rust
use tabled::{builder::Builder, settings::{Modify, Color}};

fn main() {
    let mut builder = Builder::new();
    builder.push_record(["Foo"]);
    builder.push_record(["Longer"]);
    let mut table = builder.build();
    table.with(Modify::new((0, 0)).with(Color::BG_BLUE));

    println!("{}", table);
}
```

Produces:
![image](https://github.com/zhiburt/tabled/assets/568036/e9faef25-b0b3-42fb-983e-356feff4ef6f)

However, I would like to produce
![image](https://github.com/zhiburt/tabled/assets/568036/849a00ab-c141-4528-96d3-4a06c22b0859)

Is this currently possible?
Otherwise, I think an option to do it should be added.

**Comment by zhiburt** [comment]
OK; It took longer then it should to ....

But here it is.

https://github.com/zhiburt/tabled/blob/48dd68bfc70ff1b7fc3eba77ece1c15928b06b67/tabled/src/settings/formatting/justification.rs#L37-L56

It yet not published but you can use the git version

cc: @tyilo

**Comment by zhiburt** [comment]
Thanks for originally issuing it.

**Comment by tyilo** [comment]
Thanks! :)
