### ISSUE TITLE
Typo in lib.rs line 72 - "almoust" should be "almost"

### ISSUE THREAD

**Issue by oliashish** [zhiburt/tabled#355]
I was using the `tabled` crate for my terminal-based application for the first time and while going through the documentation, I came across a typo in the `lib.rs` file on line 72. The word "almoust" is used, but it appears to be a misspelling of "almost." I've looked up the term, and it does not seem to exist in the English language. I'm not sure if that is intentional, but if it is a typo then I would be ready to fix it and contribute.
Thanks

**Comment by zhiburt** [comment]
Hi @oliashish yes, it is
(I'd bet there are plenty of these... there).

Thanks for noticing.

You're welcome to do a PR if you have spare time.

Take care.
