### ISSUE TITLE
`table.is_empty()` on tables with only a header row

### ISSUE THREAD

**Issue by pjhades** [zhiburt/tabled#363]
Hi, I run into a situation where I need to check if a table with a header row is empty. I notice that `table.is_empty()` returns false if the table has no data rows but merely a header row. However the function returns true if the table is indexed:

```rust
use tabled::{builder::Builder, settings::Style};

fn main() -> Result<()> {
    let mut builder = Builder::default();
    builder.set_header(["color", "vegetable", "contains"]);
    let builder = builder.index().column(1).name(None);
    let table = builder.build();
    assert!(table.is_empty());

    let mut builder = Builder::default();
    builder.set_header(["color", "vegetable", "contains"]);
    let table = builder.build();
    assert!(!table.is_empty());

    Ok(())
}
```
The difference seems to be caused by that `IndexBuilder` takes ["data length"](https://github.com/zhiburt/tabled/blob/master/tabled/src/builder/index_builder.rs#L229-L230) into consideration. Is this difference by-design or should non-indexed tables do the same too?

**Comment by zhiburt** [comment]
Hi @pjhades 

Seems like a bug to me.
Good catch.
Thank you for casting a light on it.

I think that `Builder::is_empty`s shall return true, if there's no data, even though there might be index/header set.
But `Table::is_empty` shall return is empty if it does not have any data.

> The difference seems to be caused by that IndexBuilder takes ["data length"](https://github.com/zhiburt/tabled/blob/master/tabled/src/builder/index_builder.rs#L229-L230) into consideration.

It's fine.

But it's an issue in the `IndexBuilder` indeed.

```rust
            // when we push a row it works
            let mut builder = Builder::default();
            builder.push_record(["color", "vegetable", "contains"]);
            let table = builder.index().build();

            assert_eq!((2, 4), table.shape());

            // But when set a header we lose it
            let mut builder = Builder::default();
            builder.set_header(["color", "vegetable", "contains"]);
            let table = builder.index().build();

            assert_eq!((0, 0), table.shape());
       
            // we lose it even on back conversion to general Builder
            let mut builder = Builder::default();
            builder.set_header(["color", "vegetable", "contains"]);
            let table = Builder::from(builder.index()).build();

            assert_eq!((0, 0), table.shape());
```

so this would be true

```rust
            let mut b1 = Builder::default();
            b1.set_header(["color", "vegetable", "contains"]);

            let b2 = Builder::from(b1.clone().index());

            assert_eq!(b1.clone().build().shape(), b2.clone().build().shape());
            assert_eq!(b1.clone().build().to_string(), b2.clone().build().to_string());
```

What do you think?

And don't you wanna make patch for it @pjhades?

**Comment by pjhades** [comment]
Thanks for providing the context! I'd love to work out a PR, but I need a bit of clarification first, just to make sure I understand the desired behaviour.

When a table is not indexed, has a header, and doesn't have data, currently its shape will include the header row. Thus `is_empty()` will return `false`. It feels a bit confusing because 1) the table actually has no data, and 2) the behaviour is different from an indexed table. For 2), I think we're on the same page: we'd like to achieve the same behaviour with `is_empty()`.

For 1), I'm thinking about either
- having `is_empty()` return true so that it doesn't count the header row against the row count, or
- keeping `is_empty()` as is but adding a new function - like `has_data()` - that would return true in this case.

Another thing I'm not sure about is that, when a table is not indexed, has a header, and doesn't have data, if we call `index()`, should `IndexBuilder` take the header row into consideration? If so, what would the desired shape be, like the `???` in the following code?
```rust
let mut builder = Builder::default();
builder.set_header(["color", "vegetable", "contains"]);
let table = builder.index().build();
assert_eq!(???, table.shape());
```

**Comment by zhiburt** [comment]
> , currently its shape will include the header row. Thus is_empty() will return false

true

> It feels a bit confusing because 1) the table actually has no data

I think it's fine, if we talk about `Table`, as it has data in my opinion.

But I'd add a new method `is_empty` to `Builder` and `IndexBuilder` which would return `false` in all cases if there's no actual data. (so as you're saying even it there will be index/header it will return `false`)

>  If so, what would the desired shape be, like the ??? in the following code?

I'd say so.
Notice 4 columns, cause of the empty cell produced by index. 

> ```rust
> let mut builder = Builder::default();
> builder.set_header(["color", "vegetable", "contains"]);
> let table = builder.index().build();
> assert_eq!((1, 4), table.shape());
> ```
