### ISSUE TITLE
Does not build on MacOS

### ISSUE THREAD

**Issue by inferiorhumanorgans** [zhiburt/tabled#376]
llogiq/bytecount#90

**Comment by zhiburt** [comment]
Hi @inferiorhumanorgans 

Interesting;

Thanks for report;

If it'll be hard to fix we could patch it to not rely on it on macos.
Or hide it after a feature flag.

Let me know if it's urgent for you.

**Comment by inferiorhumanorgans** [comment]
Ah, it's not urgent.

**Comment by inferiorhumanorgans** [comment]
Looks like it's been resolved with rust-lang/rust#118124
