### ISSUE TITLE
Using color for part of the text in a cell causes formatting issue

### ISSUE THREAD

**Issue by fbonin** [zhiburt/tabled#401]
Using color for part of the text in a cell causes formatting issue. The issue also happens with libraries like `owo-colors` or `colored`

### To reproduce 
```
fn main() {
    use tabled::{Table, Tabled};

    #[derive(Tabled)]
    struct Language {
        name: String,
        designed_by: String,
        invented_year: usize,
    }

    let languages = vec![
        Language{
            name: "Rust".to_string(),
            designed_by: format!("{} {}", "Graydon", "\x1b[31mHoare\x1b[0m"),
            invented_year: 2010
        },
    ];

    let table = Table::new(languages).to_string();
    
    println!("{}",table);
}
```

### Bug
```
+------+----------------------+---------------+
| name | designed_by          | invented_year |
+------+----------------------+---------------+
| Rust | Graydon Hoare | 2010          |
+------+----------------------+---------------+
```
<img width="399" alt="image" src="https://github.com/zhiburt/tabled/assets/732394/00346685-ea04-48cf-96e9-631cb3874af5">

### Expected
```
+------+----------------------+---------------+
| name | designed_by          | invented_year |
+------+----------------------+---------------+
| Rust | Graydon Hoare        | 2010          |
+------+----------------------+---------------+
```

**Comment by zhiburt** [comment]
Hi @fbonin 

I do bet there's no actual issue.
I think you have just forgotten to use `ansi` feature.

```toml
[dependencies]
tabled = { version = "0.15", features = ["ansi"] }
```

See

![image](https://github.com/zhiburt/tabled/assets/20165848/f8639b66-e071-4976-b529-48e68b49fcf4)

**Comment by fbonin** [comment]
I confirm that it fixes my issue. 

Thank you very much !

**Comment by zhiburt** [comment]
Hi @thermoweb well it must be there 😅 

But I am very concerned that the documentation as well as examples are somewhat feel bloated.
Please could you open an PR with improvement how you see it?

**Comment by thermoweb** [comment]
Ok I'll see what I can do :)
