### ISSUE TITLE
clippy and tests fail due to simple problems

### ISSUE THREAD

**Issue by strange-dv** [zhiburt/tabled#414]
This issue is more of a way to understand the status of this project, as I love it and want to contribute by fixing some bugs. However, I found out that `cargo test` and `clippy` and thus CI don't work due to simple code errors.

Why is everyone ignoring them? Is it intentional or is it okay if someone fixes these errors?

**Comment by zhiburt** [comment]
Hi @strange-dv 

Yes;
The `clippy` and tests fails came up by themselfs a few month ago, to be honest I am not sure even why.
Seemingly updated clippy; but why test got to fail that's very very interesting, I haven't checked to be brutally honest.

I am not ignoring it.
I am aware of it.

I just have some OLD (VERY OLD) (a few months ....) patch I must have to complete......
But very interesting patch (at least 3 important ones)
But I ...... just .... can't get it done........sooooon hopefully....


So if you @strange-dv  want you can peek it up, it'd be great.
You can ping me if you'll got some issues.

**Comment by strange-dv** [comment]
thanks for the answer! I'll try to pick it up!
