### ISSUE TITLE
`proc-macro-error` is unmaintained

### ISSUE THREAD

**Issue by LesnyRumcajs** [zhiburt/tabled#425]
This project depends on `proc-macro-error` which is reported as unmaintained and causes `cargo audit` failures in projects that use `tabled`. It would be beneficial to the consumers of this crate to fix that dependency, e.g., by switching to something else or working around it.

See https://rustsec.org/advisories/RUSTSEC-2024-0370

**Comment by zhiburt** [comment]
Thanks for pointing it out.
Agreed it must be addressed.
