### ISSUE TITLE
upgrade papergrid to a later version of unicode-width

### ISSUE THREAD

**Issue by fdncred** [zhiburt/tabled#426]
@zhiburt we're running into issues with nushell. we can't upgrade to crossterm 28.1 and ratatui 28.1. I think this is because tabled has a dep on papergrid which locks the unicode-width dep at 0.1.11. Would you mind updating papergrid/tabled with a later version?

https://github.com/zhiburt/tabled/blob/300c07bd53c945671e8115811c1689cb1353feff/papergrid/Cargo.toml#L16

**Comment by zhiburt** [comment]
Yep....................
..........................
..........................

Something I must do.
I'll ponder about it in short, hopefully.

To be honest I haven't had a good idea how to fix it.
Though wasn't thinking a lot :)

ref #423

**Comment by zhiburt** [comment]
Hi  

What do you think if I just fork `unicode-width` and that's it? :smile:

**Comment by zhiburt** [comment]
Somewhat I started to think that maybe this https://github.com/nushell/nushell/issues/13088#issuecomment-2226557157 was not an actual issue.

At this point.
Seems like I haven't investigated it deep enough.

**Comment by fdncred** [comment]
maybe there's some other crate other than unicode-width that you can use? I'm not sure such a thing exists. It's a pain not being able to update ratatui and other deps. If you fork unicode-width, you could rename it to tabled-unicode-width so that it doesn't conflict with the other one maybe?

**Comment by zhiburt** [comment]
> If you fork unicode-width, you could rename it to tabled-unicode-width so that it doesn't conflict with the other one maybe?

Exactly
And it's a 5 minute job.

**Comment by fdncred** [comment]
I think you should go ahead and do it. The worst that can happen is that you have to revert or change it. It's just software, it can be changed again.

**Comment by joshtriplett** [comment]
I've read through the entirety of https://github.com/unicode-rs/unicode-width/issues/55 and https://github.com/unicode-rs/unicode-width/issues/64 , and as far as I can tell, I think the new behavior of unicode-width is *more correct* for tabled's purposes (e.g. handling the width of emoji correctly), *as long as* tabled never feeds control characters to unicode-width. (For control characters, unicode-width will *guess* that the terminal might choose to render a character-sized replacement character, but some terminals may not render such characters at all; there's no consistent answer here other than to not handle control characters. I think it'd be reasonable to tell people to just not put control characters into table cells and expect reasonable results.)

Rather than forking unicode-width to preserve the old behavior (which was incorrect for, among other things, many composed emoji using ZWJ), I think it would make sense to port to the *new* behavior of unicode-width and have a dependency on that version of unicode-width.

**Comment by joshtriplett** [comment]
I've published a PR at https://github.com/zhiburt/tabled/pull/430 to use current unicode-width and improve width handling.

**Comment by joshtriplett** [comment]
I think this issue can now be closed.

**Comment by zhiburt** [comment]
Must be released;
Eventually :sweat_smile: 

```toml
tabled = "=0.17.0"
```

Thanks @joshtriplett once again.

**Comment by reneleonhardt** [comment]
Does this mean common control characters like tabulator and linebreak shouldn't be used in table cells either?

**Comment by zhiburt** [comment]
> Does this mean common control characters like tabulator and linebreak shouldn't be used in table cells either?

I am not sure what you imply.
Maybe it was worth to open a new issue(question) for it :)

But I got to clarify one thing you mentioned and it's completely right.

"All" UTF-8 must be allright.
*You should read most :)
*currently there's some known issues with cyrilic chars; yet unfixed.....hopefully in a few days...............always say the same thing 😞

But specifically 'tabulator' and 'linebreak' are not handled.
Intentionally.
To not bind all uses have wasted `if` statements in case there data does not contain these.
So these 2 specific ones shall be treated before hand to properly work.
For this reason `tabled::settings::formatting::Charset` was created.

```rust
use tabled::{assert::assert_table, settings::formatting::{Charset, TabSize}, Table};

fn main() {
    let t = Table::new(["Rene Leonhardt", "reneleonhardt"]);
    assert_table!(
        t,
        "+----------------+"
        "| &str           |"
        "+----------------+"
        "| Rene Leonhardt |"
        "+----------------+"
        "| reneleonhardt  |"
        "+----------------+"
    );

    let mut t = Table::new(["Rene\tLeonhardt", "reneleonhardt"]);
    assert_table!(
        t,
        "+----------------+"
        "| &str           |"
        "+----------------+"
        "| Rene\tLeonhardt |"                   // SEE ONE ISSUE HERE
        "+----------------+"
        "| reneleonhardt  |"
        "+----------------+"
    );

    t.with(TabSize::new(4));
    assert_table!(
        t,
        "+-------------------+"
        "| &str              |"
        "+-------------------+"
        "| Rene    Leonhardt |"                 // SEE WE GET IT FIXED
        "+-------------------+"
        "| reneleonhardt     |"
        "+-------------------+"
    );

    let mut t = Table::new(["Rene\r\r\rLeonhardt", "reneleonhardt"]);
    
    // On terminal the table will look as the next one
    // +------------------+
    // | &str             |
    // +------------------+
    // Leonhardt |
    // +------------------+
    // | reneleonhardt    |
    // +------------------+
    assert_table!(
        t,
        "+------------------+"
        "| &str             |"
        "+------------------+"
        "| Rene\r\r\rLeonhardt |"                           // SEE COMPLETELY BROKEN TABLE
        "+------------------+"
        "| reneleonhardt    |"
        "+------------------+"
    );

    t.with(Charset::clean());
    assert_table!(
        t,
        "+---------------+"
        "| &str          |"
        "+---------------+"
        "| ReneLeonhardt |"                                 // SEE ALL THESE /r occurences were removed
        "+---------------+"
        "| reneleonhardt |"
        "+---------------+"
    );
}
``

cc: @reneleonhardt 

PS: As a side note; I am not very satisfied with current implementation of this at least cause for proper work we need 2 pathes now over data. Meaning we could make `Charset` something like a builder and it would be a bit more efficient. One more on a todo list.
