### ISSUE TITLE
Table format settings were ignored after line wrap

### ISSUE THREAD

**Issue by eatradish** [zhiburt/tabled#427]
My settings are as follows:

```rust
        table
            .with(Modify::new(Segment::all()).with(Alignment::left()))
            .with(Modify::new(Columns::new(2..3)).with(Alignment::left()))
            .with(Style::psql())
            .with(Modify::new(Segment::all()).with(Format::content(|s| format!(" {s} "))))
            .with(Width::wrap(WRITER.get_length() as usize).priority::<PriorityMax>().keep_words());
```

Output:

![图片](https://github.com/user-attachments/assets/dc1102d3-15fe-4830-bcd8-670937caf13d)

Namely, for gnuplot, the text "PostScript, PNG, GIF and others" seems to have ignored `Modify::new(Segment::all()).with(Format::content(|s| format!(" {s} ")))` , making the indentation inconsistent.

**Comment by eatradish** [comment]
It seems like I'm using the wrong method, it looks like I should be using `Padding`

**Comment by zhiburt** [comment]
Hi @eatradish 

> It seems like I'm using the wrong method, it looks like I should be using `Padding`

Likely so,
Did you resolved your issue, or may I help?

**Comment by zhiburt** [comment]
Notes about clean code:

```rust
# instead of this you could use
.with(Modify::new(Segment::all()).with(Alignment::left()))
# this
.with(Alignment::left())

# and instead of this
.with(Modify::new(Columns::new(2..3)).with(Alignment::left()))
# this
.modify(Columns::new(2..3), Alignment::left())
```

**Comment by eatradish** [comment]
> Hi @eatradish 
> 
> 
> 
> > It seems like I'm using the wrong method, it looks like I should be using `Padding`
> 
> 
> 
> Likely so,
> 
> Did you resolve your issue, or may I help?

I solved my problem with Padding, the code is here:

https://github.com/AOSC-Dev/oma/blob/e2b02d26c6e0155dab7a0eb63b85c7986545b7a3/src/table.rs#L162

thanks!
