### ISSUE TITLE
Unable to use tabled-derive because of unmaintained proc-macro-error 

### ISSUE THREAD

**Issue by martintmk** [zhiburt/tabled#452]
We are trying to use this crate but are unable to do so because it uses the `proc-macro-error` which is not maintained anymore.

https://rustsec.org/advisories/RUSTSEC-2024-0370 

Would it be possible to switch to maintained alternarive? For example: https://crates.io/crates/manyhow

**Comment by zhiburt** [comment]
Hi @martintmk 

I think it must be addressed already https://github.com/zhiburt/tabled/pull/428
The only thing is that it was not released yet.

I do hope to do it soon.
Maybe even this week.
Just wanna be sure some minor things were addressed.

**Comment by zhiburt** [comment]
If you're OK to use github instead of crates.io for a bit you can use the next one.

```toml
tabled = { git = "https://github.com/zhiburt/tabled", rev = "660d25659d9b05eef33a12dd8b512e99ef54d4ac" }
```

**Comment by martintmk** [comment]
Thanks @zhiburt , this is fine then, will just wait for a next release :)
