### ISSUE TITLE
tabled 0.17.0 trait not implemented anymore

### ISSUE THREAD

**Issue by matthieugouel** [zhiburt/tabled#463]
Hey 👋 

Renovate is trying to update tabled to 0.17.0 for this [project](https://github.com/nxthdr/chbot) but the build CI fails with this error: 

```
114 |         .with(Style::sharp())
    |          ---- ^^^^^^^^^^^^^^ the trait `for<'a> tabled::settings::table_option::TableOption<papergrid::records::vec_records::VecRecords<papergrid::records::vec_records::cell_info::Text<std::string::String>>, tabled::grid::config::colored_config::ColoredConfig, tabled::grid::dimension::complete_dimension_vec_records::CompleteDimensionVecRecords<'a>>` is not implemented for `tabled::settings::Style<On, On, On, On, (), On, 1, 0>`
```

It corresponds to this line: https://github.com/nxthdr/chbot/blob/main/src/main.rs#L114 setting the style. 
Should I change the code or is it a bug introduced with the new version? 

Thanks!

**Comment by zhiburt** [comment]
Sorry for inconveniences.
To be honest I quite dislike the current versioning logic.... but I did not came up with more friendly one yet.

The issue you got is 2 PRs which are changing crates separately.
If you'd merge them it would be all right :smile: 

I mean they just need to be updated simultaneously.

Have a great Sunday.

**Comment by matthieugouel** [comment]
Thank you very much for you help and your PR @zhiburt ! 
Have a great Sunday too.
