### ISSUE TITLE
tabled_derive v0.1.9 update introduced a semver-incompatible change

### ISSUE THREAD

**Issue by Disasm** [zhiburt/tabled#49]
Now it implements the `LENGTH` associated constant which is missing from tabled v0.3.0. This results in broken builds for other projects (try `cargo install cargo-bom`). I'd suggest yanking tabled_derive v0.1.9 and releasing tabled_derive v0.2.0 with subsequent update to tabled.

**Comment by zhiburt** [comment]
Hi @Disasm,

> Now it implements the LENGTH associated constant which is missing from tabled v0.3.0.

True 

> This results in broken builds for other projects (try cargo install cargo-bom)

That's interesting but,
I actually can't see how it could happen because the trait itself is inside a `tabled` crate.

**Comment by zhiburt** [comment]
But I see that it fails.
That's strange

**Comment by zhiburt** [comment]
Aaaaaa now I see

**Comment by zhiburt** [comment]
That's actually a huge issue....
Thank you for pointing this up.

**Comment by zhiburt** [comment]
It made me nervous a little bit.
But it supposed to be done.

Can you verify it?

**Comment by zhiburt** [comment]
Now for sure I hope.

It took me 2 versions of `tabled` to make it right.... :disappointed_relieved:

**Comment by Disasm** [comment]
Now everything seems to be working, thank you a lot!

**Comment by zhiburt** [comment]
Well thank you a lot.
And sorry that I did not respond faster.
Just haven't noticed it in notifications.

By the way.
Happy New Year.

**Comment by Disasm** [comment]
Happy New Year!
