### ISSUE TITLE
Add an option to avoid line-breaking in the middle of a word

### ISSUE THREAD

**Issue by mrjones2014** [zhiburt/tabled#57]
Currently I'm just putting some extra space in my strings so that the whole word gets wrapped to next line instead of line-wrapping in the middle of a word.

It would be cool to have an option to automatically line-wrap at word boundaries.

**Comment by zhiburt** [comment]
Hello @mrjones2014 

So essentially (correct me if I mistake) you propose to have an option to wrap string by words, like `MaxWidth` does with width correct?

Example

```rust
Table::new(&["hello world", "123"])
   .with(Modify::new(Full).with(Wrap::words));
```

```
┌───────┐
│ &str  │
├───────┤
│ hello │ 
│ world │
├───────┤
│  123  │ 
└───────┘

```

**Comment by mrjones2014** [comment]
Yep exactly. Currently, depending on the width value you set, you might end up with a result like:

```
┌─────────┐
│ &str    │
├─────────┤
│ hello w │ 
│ orld    │
├─────────┤
│  123    │ 
└─────────┘
```

But it would be nice to have an option to make it break on word boundaries like the result you've posted above.

**Comment by zhiburt** [comment]
> Yep exactly. Currently, depending on the width value you set, you might end up with a result like:

True

Overall I think we could do it.

But you could reach the same affect by doing the following.

```rust
Table::new(&["hello world", "123"])
   .with(Modify::new(Full).with(|s: &str| s.split_whitespace().join("\n")));
```

*It doesn't handle colors.

Do you think shall it be included?
If you do you are satisfied with the interface I was providing you with? 

> ```rust
>  Table::new(&["hello world", "123"])
>     .with(Modify::new(Full).with(Wrap::words));
> ```

**Comment by mrjones2014** [comment]
```rust
Table::new(&["hello world", "123"])
   .with(Modify::new(Full).with(|s: &str| s.split_whitespace().collect::<Vec<_>>().join("\n")));
```

wouldn't that put each word on it's own line? that's not really what I want.

Maybe a clearer representation, this can happen currently:

```
┌───────────────────┐
│ &str              │
├───────────────────┤
│ this is a long se │ 
│ ntence            │
└───────────────────┘
```

but it should ideally look like this:

```
┌───────────────────┐
│ &str              │
├───────────────────┤
│ this is a long    │ 
│ sentence          │
└───────────────────┘
```

**Comment by zhiburt** [comment]
Ohh now I see,


Yes that's a little bit different.

Then it becomes interesting :smile: 

I guess we could try to do that.

But what if there will be one long like 

```
┌─────────────────────┐
│ &str                │
├─────────────────────┤
│ thisisalongsentence │
└─────────────────────┘
```

And you want to wrapp it like

```rust
MaxWidth::wrapping(3, "").keep_words()
```

we would not change anything right?

A thought: theoretically we could even handle syntax wrapping as an option.

Like this

```text
wrap-
ping text.
```

**Comment by mrjones2014** [comment]
Yeah, there might need to be some heuristics around if the word exceeds a certain length then it's okay to line-wrap it maybe? In that case, wrapping with hyphenation would be ideal, I think.

**Comment by zhiburt** [comment]
> Yeah, there might need to be some heuristics around if the word exceeds a certain length then it's okay to line-wrap it maybe

Not sure about heuristics but we could at least use an optional argument like.

```rust
MaxWidth::wrapping(3, "").keep_words().force_wrap(3)
```

> In that case, wrapping with hyphenation would be ideal, I think.

Do you feel like it must handle syntax then?

Not easy thing to do if follow actual grammar rules. (Which I personally not a big fun as I might noticed :sweat_smile:)
And if we do the former issue remains still.

It may worth it to use https://github.com/mgeisler/textwrap if we wanna handle actually syntax. 
But If we do I would probably hide it via `feature`.

If there's no need for syntax we could handle it in house

**Comment by mrjones2014** [comment]
I don't necessarily think we need to obey language syntax. If using a hyphen proves to add a lot of complexity, I don't think it's needed.

`force_wrap(n)` is this intended to be "force wrap if the word is longer than `n` characters long?"

**Comment by zhiburt** [comment]
> `force_wrap(n)` is this intended to be "force wrap if the word is longer than `n` characters long?"

Exactly

The interface might got a little bit too verbose, but the idea is here

**Comment by mrjones2014** [comment]
I think you could just include a parameter for `.keep_words(n)` where `n` is the max length of words to preserve.

**Comment by zhiburt** [comment]
OK I'll try to work on it in the nearest.

Thank you for opening the issue

**Comment by zhiburt** [comment]
Hey @mrjones2014 It took me a while to get to this.
Sorry for the delay.

Could you verify that it works like you expect?

You can use the following change in `Cargo.toml`

```toml
tabled = { git = "https://github.com/zhiburt/tabled/", branch = "word_width_control" }
```

**Comment by zhiburt** [comment]
Thank's for your verification.

I'll try to not forget 👍 

PS: The issue will be closed once I merge the PR into master

**Comment by mrjones2014** [comment]
hey @zhiburt thanks for implementing this! any idea when it will be released to the crate registry?

**Comment by zhiburt** [comment]
@mrjones2014 Just published it 

https://crates.io/crates/tabled
