### ISSUE TITLE
Disable headers?

### ISSUE THREAD

**Issue by numToStr** [zhiburt/tabled#7]
Thanks for making this beautiful crate ❤️ . I am very much enjoying working with it.

So, It there any way to disable/remove the headers completely. In my use case headers don't make that much sense.

For example, I am printing a table like this

- Code
```rust
let details = [
    ("Username", "username"),
    ("Password", "password"),
    ("URL", "url"),
    ("Notes", "notes"),
];

let table = table!(
    &details,
    Style::PseudoClean,
    HorizontalAlignment::new(Alignment::Left, AlignmentObject::Full),
    ChangeRing(Row(1..), vec![Box::new(|s| format!(" {} ", s))])
);

println!("{}", table);
```

- Output
```
┌──────────┬──────────┐
│&str      │&str      │
├──────────┼──────────┤
│ Username │ username │
│ Password │ password │
│ URL      │ url      │
│ Notes    │ notes    │
└──────────┴──────────┘
```

- Wanted
```
┌──────────┬──────────┐
│ Username │ username │
│ Password │ password │
│ URL      │ url      │
│ Notes    │ notes    │
└──────────┴──────────┘
```

Maybe there is already a way to disable headers but I wasn't able to find it in the docs.

**Comment by zhiburt** [comment]
Hi @numToStr, appreciate your words, thank you
It's an interesting case there's no such an option currently but I certainly can work on it.

PS: Just publish a option for disabling columns via attributes.

```rust
        #[derive(Tabled)]
        enum Letters {
            Vowels {
                character: char,
                lang: u8,
            },
            Consonant(char),
            #[header(hidden)]
            Digit,
        }
```

**Comment by zhiburt** [comment]
> So, is it published on crates?

Not yet, planning later this day as there's a couple more things to tackle.

**Comment by numToStr** [comment]
Thanks for letting me know. Waiting for the next release ✌🏻.

**Comment by zhiburt** [comment]
I've add a `Dissable` setting which partially solves the problem.

According to a style I'll inspect some ways to bypass this and return with the answer. 

https://github.com/zhiburt/tabled/blob/08ee2ade35b8f5b6749805f28edd469b7662a6d6/tests/disable_test.rs#L60-L93

**Comment by numToStr** [comment]
Just saw the test and I think `Dissable::Row(..1)` solves the use case.

Off topic: Why did you name it `Dissable` not `Disable`?

**Comment by zhiburt** [comment]
> Just saw the test and I think Dissable::Row(..1) solves the use case.

It is the only thing is a different look of a first row.

> Off topic: Why did you name it Dissable not Disable?

Clearly misspell it :face_with_head_bandage: .
Already fixed. Good catch.

**Comment by zhiburt** [comment]
I've just published customization for `Style`.
And getting back to your example now you can achieve it by combining custom styles + disable.

```rust
    let table = table!(
        &data,
        HorizontalAlignment(Full, Alignment::Left),
        Disable::Row(..1),
        Style::pseudo_clean().header(None),
    );
```

Output

```
┌────────┬────────┐
│Username│username│
│Password│password│
│URL     │url     │
│Notes   │notes   │
└────────┴────────┘
```

@numToStr please mark an issue as resolved if you think it is.

**Comment by numToStr** [comment]
Thanks for the update. I'll try the new release and report back.

**Comment by numToStr** [comment]
@zhiburt Did you publish the update?

**Comment by zhiburt** [comment]
> @zhiburt Did you publish the update?

It's supposed to be in a few minutes

**Comment by numToStr** [comment]
@zhiburt Thank you so much. `v.0.1.3` does solve my use case.

Here is the final code
- Code
```rust
#[derive(Tabled)]
struct Detail(&'static str, String);

let details = [
    Detail("Username", "username".to_string()),
    Detail("Password", "password".to_string()),
    Detail("URL", "url".to_string()),
    Detail("Notes", "notes".to_string()),
];

let table = table!(
    &details,
    Disable::Row(..1),
    Style::pseudo_clean().header(None),
    HorizontalAlignment(Row(..), Alignment::Left),
    Format(Row(..), |s| format!(" {} ", s))
);

print!("{}", table);
```
- Output
```
┌──────────┬──────────┐
│ Username │ username │
│ Password │ password │
│ URL      │ url      │
│ Notes    │ notes    │
└──────────┴──────────┘
```

I'll now close the issue.

**Comment by inferiorhumanorgans** [comment]
This doesn't appear to work (for me).

```rust
    let mut builder = Builder::default();
    builder.push_record(&["a", "b", "c"].map(str::to_owned));
    builder.push_record(&["a", "b", "c"].map(str::to_owned));
    builder.push_record(&["a", "b", "c"].map(str::to_owned));
    builder.push_record(&["a", "b", "c"].map(str::to_owned));
    let table = builder
        .build()
        .with(Style::rounded())
        .with(Disable::row(Rows::single(0)))
        .with(BorderSpanCorrection)
        .to_string();
```

```
╭───┬───┬───╮
│ a │ b │ c │
├───┼───┼───┤
│ a │ b │ c │
│ a │ b │ c │
╰───┴───┴───╯
```

**Comment by zhiburt** [comment]
Hi @inferiorhumanorgans 

But what you was expecting to get?

If you want to remove the horizontal line you shall use something like this.

```rust
    use tabled::{
        builder::Builder,
        settings::{object::Rows, Disable, Style},
    };

    let mut builder = Builder::default();
    builder.push_record(["a1", "b1", "c1"]);
    builder.push_record(["a", "b", "c"]);
    builder.push_record(["a", "b", "c"]);
    builder.push_record(["a", "b", "c"]);

    let mut table = builder.build();
    table
        .with(Style::rounded().remove_horizontals())
        .with(Disable::row(Rows::single(0)));

    println!("{table}");
```

```text
╭───┬───┬───╮
│ a │ b │ c │
│ a │ b │ c │
│ a │ b │ c │
╰───┴───┴───╯
```

**Comment by inferiorhumanorgans** [comment]
I was hoping to see no horizontal line.  My eventual goal was to have a two row header at the top.  My solution was to call `remove_horizontals` and add one in at the right position.

**Comment by zhiburt** [comment]
So something like this?

```rust
    use tabled::{builder::Builder, settings::Style};

    let mut builder = Builder::default();
    builder.push_record(["a1", "b1", "c1"]);
    builder.push_record(["a", "b", "c"]);
    builder.push_record(["a", "b", "c"]);
    builder.push_record(["a", "b", "c"]);

    let mut table = builder.build();
    table.with(
        Style::rounded()
            .remove_horizontals()
            .horizontals([(2, HorizontalLine::inherit(Style::modern()))]),
    );

    println!("{table}");
```

```text
╭────┬────┬────╮
│ a1 │ b1 │ c1 │
│ a  │ b  │ c  │
├────┼────┼────┤
│ a  │ b  │ c  │
│ a  │ b  │ c  │
╰────┴────┴────╯
```

**Comment by inferiorhumanorgans** [comment]
This is what I ended up with:

https://git.sr.ht/~az1/glyph-inspect

<img width="596" alt="361998665-41757b86-8c33-4d7f-90fc-f0d10adb4ab3" src="https://github.com/user-attachments/assets/bb175c75-8c37-44b7-a30a-03425f7d68fe">

**Comment by zhiburt** [comment]
@inferiorhumanorgans

just in case, I want to let you know that you can use `Span` to combine cells together and then apply `Alignment` in case you want to.
