### ISSUE TITLE
Provide a way to deal with types that don't implement Display

### ISSUE THREAD

**Issue by nicoulaj** [zhiburt/tabled#8]
For instance:
```
#[derive(Tabled)]
pub struct MyRecord {
    pub id: i64,
    pub valid: Option<bool>
}
```

I can't implement `Display` for `Option<bool>`, so I'm stuck here (`[E0117]: only traits defined in the current crate can be implemented for arbitrary types`). I cannot use another type either.

Some possible ideas:

- allow to switch to `Debug` instead of `Display` for the whole struct ?
- same, on a per field basis ?
- allow me to provide my own display trait, so I can implement it on arbitrary types ?

**Comment by zhiburt** [comment]
Hello @nicoulaj, 
Could you clarify a bit your 3rd idea?

I can state that there's 2 ways how to solve this issue currently.

* Implement `Tabled`  trait manually for a `MyRecord` type.
* Wrap `Option` to something like `DisplayedOption<T>(Option<T>)` and implement a `Display` trait for it.

What do you think @nicoulaj ?

**Comment by zhiburt** [comment]
I've just published a feature for resolving this issue.
Add a `#[field(display_with="display_option")]` to an `Option` field.

```rust
fn display_option(o: &Option<bool>) -> String {
    match o {
        Some(s) => format!("some {}", s), 
        None => format!("none"),
    }
}

#[derive(Tabled)]
pub struct MyRecord {
    pub id: i64,
    #[field(display_with="display_option")]
    pub valid: Option<bool>
}
```

**Comment by zhiburt** [comment]
@nicoulaj Please mark the issue as closed if it's supposed to be.

And thank you for opening this issue :+1:
