### ISSUE TITLE
Create a `CustomStyle::frame` function which returns `Border` of its frame.

### ISSUE THREAD

**Issue by zhiburt** [zhiburt/tabled#94]
It could be useful to be able to get a `Border` of a frame of a particular style.
So we could use it as general `Border` and `Highlight`.

https://github.com/zhiburt/tabled/blob/13028fb68eba25a7b9ac41b3630fc8a16d1faabc/src/style.rs#L263

The exposure could be done via a constant of function.

Not sure what is the best public interface for it.

**Comment by IsaacCloos** [comment]
Could it be worth having a function to return the style assigned to a table as a whole?

Example:

```rust
let table = Table::new(&data)
        .with(Style::modern());

let style = table.get_style(); // returns assigned StyleSetting from grid

assert(style, Style::Modern)
```

This could allow for such functions as:
- `get_style()`
- `reapply_style()` Could be useful for refinishing after doing `Extract`
- `style_to_pattern()` referencing #46 
- `style_to_char_array()` not a sure if this would be helpful to anyone 😄

**Comment by zhiburt** [comment]
> Could it be worth having a function to return the style assigned to a table as a whole?
> 
> Example:
> 
> ```rust
> let table = Table::new(&data)
>         .with(Style::modern());
> 
> let style = table.get_style(); // returns assigned StyleSetting from grid
> 
> assert(style, Style::Modern)
> ```

Interesting idea.

But I don't think it's possible at least like this.
Because `StyleSetting` doesn't contains changes which could be done by a user for any cell.
Using `Border` or `Highlight`.

My original proposition was just to get a `Frame` of a table.
Because frame is present on any table.

So it could be used like this.

```rust
let table = Table::new(&data)
          .with(Style::modern());
          .with(Highlight::new(Columns::single(1), Style::ascii().frame()));
```

Something like this.

**Comment by zhiburt** [comment]
Once again actually your idea about `get_style()` is interesting but how you would handle a random changes.

Like it's clear how to handle it when tables have the same size.
But when you don't? 

In any case a new structure would need to be created then because `StyleSetting` contains only theme information not any specifics.

**Comment by zhiburt** [comment]
Original issue `CustomStyle::frame` was addressed.

The idea about `get_style` is actually something probably need to be addressed as well.
But yet not sure how it would look like.

A new issue must be created for it.
